# Generated by Django 4.2.27 on 2026-01-27 15:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Month for which budget is recommended (YYYY-MM-01)')),
                ('recommended_savings', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('savings_reason', models.TextField(help_text='Explanation for recommended savings amount')),
                ('total_recommended_budget', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, help_text="User's monthly income", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('income_stability_score', models.FloatField(default=0.0, help_text='Score from 0-100 indicating income stability')),
                ('expense_volatility_score', models.FloatField(default=0.0, help_text='Score from 0-100 indicating expense volatility (higher = more volatile)')),
                ('savings_confidence_indicator', models.FloatField(default=0.0, help_text='Score from 0-100 indicating confidence in meeting savings goals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Financial Profile',
                'verbose_name_plural': 'User Financial Profiles',
            },
        ),
        migrations.CreateModel(
            name='WeeklyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(help_text='Week number in the month (1-4 or 5)')),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('recommended_weekly_spending', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('recommended_weekly_savings', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('explanation', models.TextField(help_text='Why this weekly budget makes sense')),
                ('budget_recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_budgets', to='finance.budgetrecommendation')),
            ],
            options={
                'ordering': ['week_start_date'],
                'unique_together': {('budget_recommendation', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('merchant_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('bills', 'Bills & Utilities'), ('rent', 'Rent'), ('emi', 'EMI'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('subscriptions', 'Subscriptions'), ('other', 'Other')], max_length=50)),
                ('expense_type', models.CharField(blank=True, choices=[('fixed', 'Fixed Expenses'), ('variable_essential', 'Variable Essentials'), ('discretionary', 'Discretionary')], help_text='Fixed, Variable Essential, or Discretionary', max_length=50, null=True)),
                ('transaction_source', models.CharField(choices=[('upi', 'UPI'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('cash', 'Cash'), ('manual', 'Manual Entry')], default='manual', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_anomaly', models.BooleanField(default=False, help_text='Marks one-time large or unusual expenses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='finance_tra_user_id_3294c0_idx'), models.Index(fields=['category'], name='finance_tra_categor_afb10f_idx')],
            },
        ),
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('bills', 'Bills & Utilities'), ('rent', 'Rent'), ('emi', 'EMI'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('subscriptions', 'Subscriptions'), ('other', 'Other')], max_length=50)),
                ('recommended_limit', models.DecimalField(decimal_places=2, help_text='Recommended spending limit for this category', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actual_average', models.DecimalField(decimal_places=2, help_text='Historical average spending in this category', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('variance', models.DecimalField(decimal_places=2, help_text='Difference between recommended and actual (can be negative)', max_digits=10)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('reason', models.TextField(help_text="Explanation for this category's budget recommendation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to='finance.budgetrecommendation')),
            ],
            options={
                'ordering': ['category'],
                'unique_together': {('budget_recommendation', 'category')},
            },
        ),
        migrations.AddIndex(
            model_name='budgetrecommendation',
            index=models.Index(fields=['user', 'month'], name='finance_bud_user_id_4a2a5e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetrecommendation',
            unique_together={('user', 'month')},
        ),
    ]
